### ISSUE TITLE
Feature Request: Distribution via brew once we have a 1.0.0

### ISSUE THREAD

**Issue by dgomesbr** [iann0036/iamlive#6]
Hello,

It would be great to be able to do brew install `iamlive`. Once this reaches `1.0.0` or when you have time, would you mind updating the distribution mechanism to brew for Mac binaries?

Ref: https://medium.com/@ben.lafferty/deploying-go-cli-applications-316e9cca16a4

**Comment by tisba** [comment]
I'm happy to help here. We've been using goreleaser for multiple projects that automatically generate a formula for brew on release. Currently https://github.com/iann0036/go-release-action is used for building releases but it does not seem to support homebrew.

**Comment by iann0036** [comment]
Happy for you to propose an alternative. If you can figure out how to codesign the Darwin releases too, double points! (I have an active certificate)

**Comment by skyzyx** [comment]
See `goreleaser` and `mitchellh/gon`.

**Comment by iann0036** [comment]
Thanks for the suggestion @skyzyx. There is now a Homebrew tap option available, instructions in the README.

**Comment by FernandoMiguel** [comment]
```sh
$ brew reinstall iamlive
==> Downloading https://github.com/iann0036/iamlive/releases/download/v0.39.0/iamlive-v0.39.0-darwin-amd64.zip
Already downloaded: /Users/fernando/Library/Caches/Homebrew/downloads/2444c47064f209508488b18131f349c69cfd3ac6e54b177d73ba67f7b84dea25--iamlive-v0.39.0-darwin-amd64.zip
==> Reinstalling iann0036/iamlive/iamlive
Error: send_io() function is unimplemented on this machine
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:79:in `send_io'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:79:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:417:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:73:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
/usr/local/Homebrew/Library/Homebrew/reinstall.rb:62:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:102:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

Traceback (most recent call last):
	2: from /usr/local/Homebrew/Library/Homebrew/build.rb:221:in `<main>'
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:221:in `open'
/usr/local/Homebrew/Library/Homebrew/build.rb:221:in `recv_io': file descriptor was not passed (msg_controllen=0 smaller than sizeof(struct cmsghdr)=12) (SocketError)
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:217:in `<main>'
/usr/local/Homebrew/Library/Homebrew/build.rb:256:in `rescue in <main>': private method `puts' called for nil:NilClass (NoMethodError)
Traceback (most recent call last):
	16: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `reinstall'
	14: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:102:in `block in reinstall'
	12: from /usr/local/Homebrew/Library/Homebrew/reinstall.rb:62:in `reinstall_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:45:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:880:in `block in build'
	 1: from /usr/local/Homebrew/Library/Homebrew/sandbox.rb:99:in `exec'
/usr/local/Homebrew/Library/Homebrew/utils.rb:322:in `safe_system': Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20210712-17534-1xe6f23.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/iann0036/homebrew-iamlive/iamlive.rb` exited with 1. (ErrorDuringExecution)
	16: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `reinstall'
	14: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:96:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:102:in `block in reinstall'
	12: from /usr/local/Homebrew/Library/Homebrew/reinstall.rb:62:in `reinstall_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `rescue in block (3 levels) in safe_fork'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `puts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `write': Broken pipe (Errno::EPIPE)
```
