### ISSUE TITLE
Brew support on Linux

### ISSUE THREAD

**Issue by farzadmf** [iann0036/iamlive#66]
Hi,

`Homebrew` is also a valid installation on Linux, but seems like the current tap only supports Mac. I'd appreciate if you add Linux support as well, thank you!

**Comment by balq60** [comment]
Agreed.

I install numerous applications on linux with brew.  I have never encountered this before.

Admin:~/environment/iridium-secure-phase-1/secure-phase-1-data-transfer-v1/secure-phase-1-data-transfer/IaC/environments/2-test (features/setup) $ brew install iann0036/iamlive/iamlive
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:308:in `determine_active_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:239:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:485:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:485:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:645:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:762:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:649:in `block in formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:645:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:645:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:318:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
Admin:~/environment/iridium-secure-phase-1/secure-phase-1-data-transfer-v1/secure-phase-1-data-transfer/IaC/environments/2-test (features/setup) $

**Comment by iann0036** [comment]
Hi @farzadmf,

Apologies for the very late response.

I've now included the linux releases in the Homebrew package. Let me know if you have any issues.

**Comment by SPONGE-JL** [comment]
Hi @iann0036,

I have very similar issue in June 2025, so I had request to homebrew/install issue:

https://github.com/Homebrew/install/issues/987

**Comment by iann0036** [comment]
@SPONGE-JL I suspect [this](https://github.com/iann0036/homebrew-iamlive/commit/ce2122a0a9b63933eed709dcbc77096502d48994) might solve it? Try again for me.

**Comment by SPONGE-JL** [comment]
@iann0036 Thanks for rapid follow up.

I attached my case returned 404 error:
![Image](https://github.com/user-attachments/assets/74c72c32-8994-4072-9483-5726011149e0)

**Comment by iann0036** [comment]
Ah, good spot. Try again now?

**Comment by SPONGE-JL** [comment]
As [the document guide](https://docs.github.com/en/repositories/creating-and-managing-repositories/troubleshooting-cloning-errors#check-your-permissions) and before my experience,when `git clone` command require the Username and Password is the case that clone to private repository without permission.

Why does git require even though clone the public repository...? 🤔

**Comment by SPONGE-JL** [comment]
@iann0036 This case seems that is related my local setting. I'll feedback soon.

![Image](https://github.com/user-attachments/assets/22adb9f6-7be4-43d2-b81a-b63e2bf16012)

**Comment by farzadmf** [comment]
Just tried doing `brew install iann0036/iamlive/iamlive` on a Mac and a Linux machine, and it seems to be working 🚀

**Comment by iann0036** [comment]
Thanks all for the help on the long-standing issue!
